### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by jdalton** [hash-bang/lodash-keyarrange#1]
For reference object iteration order [is defined](http://www.ecma-international.org/ecma-262/6.0/#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys) in ES6.

**Comment by hash-bang** [comment]
Thanks for the reference but as far as I can see there isn't a way of getting a sorted object without re-creating it.

The issue I was having is caching complex objects where sometimes the keys would be out of order because an upstream process would shuffle them around.

This project was an attempt to solve that by rearranging the object into the correct key order. The additional `keyArrangeDeep` function also works on the nested values of collections / objects / arrays as needed.

**Comment by jdalton** [comment]
> Thanks for the reference but as far

But nothing :sunglasses: 

Relax, I was just giving you a reference in case you wanted to give it a readme mention or something.
Wasn't asking for you to unload.
