### ISSUE TITLE
Sorting Failed with String number

### ISSUE THREAD

**Issue by suryasarafe** [hash-bang/lodash-keyarrange#2]
I have object and want to be like this,
`{ 'Name': null, '01': null, '02': null, '03': null, '04': null, '05': null, '06': null, '07': null, '08': null, '09': null, '10': null, '11': null, '12': null, '13': null, '14': null, '15': null, '16': null, '17': null, '18': null, '19': null, '21': null, '22': null, '23': null, '24': null, '25': null, '26': null, '27': null, '28': null, '29': null, '30': null, '31': null }`

before sorting is just dynamic and just randomly sorting, and after using this plugin the result is like

`{
  '10': null,
  '11': null,
  '12': null,
  '13': null,
  '14': null,
  '15': null,
  '16': null,
  '17': null,
  '18': null,
  '19': null,
  '21': null,
  '22': null,
  '23': null,
  '24': null,
  '25': null,
  '26': null,
  '27': null,
  '28': null,
  '29': null,
  '30': null,
  '31': null,
  'Name': null,
  '01': null,
  '02': null,
  '03': null,
  '04': null,
  '05': null,
  '06': null,
  '07': null,
  '08': null,
  '09': null,
}`

the value is not like what I expecting, any idea how to make it costum.? or sort priority thing.?

**Comment by hash-bang** [comment]
@suryasarafe, it took me a bit of digging to get to the bottom of this.

It turns out that JavaScript treats any numeric key (even if its a string) as an [array insertation](https://bugs.chromium.org/p/v8/issues/detail?id=164) and remaps the output seemingly randomly as you found. See also [this answer](https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order).

I tried everything I could think of but I simply can't figure out how to not make JavaScript do this with numeric object keys. All I can really suggest here is either using a Map instead of a native object (which doesn't have this issue) or prefix your numerics with any non-numeric which fixes the issue - e.g. use `_01` intead of `01`.
